### ISSUE TITLE
MCP7940

### ISSUE THREAD

**Issue by zevero** [crako1t/MCP7940-library-for-logger#2]
My MCP7940 sets leapyear on bit 6 of the month!
So it used to work normal for quite a long time, but as of 2016 - due to the leapyear bit - it received 20 months more showing some date in 2018 or 2019...

So I propose to do

```
uint8_t m = bcd2bin(Wire.read() & 0x1F);
```

so the month is guaranteed to be smaller than 20 :)

**Comment by crako1t** [comment]
It has been a while since I looked at the code for this. Is that proposal intended as an addition? Or as a correction to an existing line? If you'd like to make the change yourself I will gladly add it to the project, otherwise direct me to where it needs to go and I can make the necessary commit.

**Comment by zevero** [comment]
My line above replaces line 162 in MCP7940.cpp.
Leapyear on bit 6 will  add 20 extra months on leapyears.
Therefor you need to  mask bit 6, which is done by  & 0x1F.

**Comment by crako1t** [comment]
Putting the necessary code together, thank you for catching that. Unfortunately the project this was put in will have the bug in their data logging. Hoping they catch that...
