### ISSUE TITLE
ESP8266 (Generic Module)

### ISSUE THREAD

**Issue by ghost** [crako1t/MCP7940-library-for-logger#4]
\MCP7940-library-for-logger-master\MCP7940.cpp:6:26: fatal error: avr/pgmspace.h: No such file or directory

 #include <avr/pgmspace.h>

                          ^

compilation terminated.

exit status 1
Error compiling for board Generic ESP8266 Module.

**Comment by crako1t** [comment]
What sort of controller are you using with the ESP8266 and MCP7940

**Comment by Tensa225** [comment]
With controller you are referring to the type of programmer?
